spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demosql
    username: root
    password: 123456
eureka:
  client:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true