spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: postgres
    password: postgres
eureka:
  client:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true